version: 2

sources:
  - name: localsource
    description: "This is customer table it contains information about the customer like name, adrress, phone number etc"
    schema: public
    tables:
      - name: customer
      - name: account
      - name: hist_transactional
      - name: branch
      - name: card
      - name: product